# Labels is an object where:
# - keys are labels
# - values are array of string patterns to match against title + body in issues/prs
labels:
  'bug':
    - '\bBUG[s]?\b'
  'enhancement':
    - '\bFEAT\b'
  'documentation':
    - '\bDOCU\b'
